name: Windows OS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up
      run: sudo apt-get install make
    - name: make
      run: make -Calender.c

